### ISSUE TITLE
【请教】关于正文中单双引号的显示问题

### ISSUE THREAD

**Issue by ArtinHuang** [hustcer/hexo-theme-air#6]
![image](https://cloud.githubusercontent.com/assets/10860203/6095923/a44ee9b0-afaf-11e4-8768-8b029a003493.png)

在windows+sublime2的环境下用Markdown编写的文档，单双引号在代码行无误，可是正文显示却出错了，请教下如何解决？

**Comment by hustcer** [comment]
像是全角半角的问题？另外你也可以试下这样:
用code标签将单双引号包裹起来 <code>'"</code>

**Comment by ArtinHuang** [comment]
嗯，听取你的建议，使用了code标签，不过显示效果没有很大改善
![Uploading 搜狗截图15年02月08日1943_1.png . . .]()

PS：强迫症患者表示有些难受

……

**Comment by ArtinHuang** [comment]
使用codo标签，效果仍然差强人意
![15 02 08 1943_1](https://cloud.githubusercontent.com/assets/10860203/6096570/1457d014-afd3-11e4-8a8a-aa54d7444476.png)

PS：强迫症患者表示鸭梨很大……

**Comment by hustcer** [comment]
你这应该是全角半角的问题吧？

**Comment by ArtinHuang** [comment]
```
最后，理解变量在计算机内存中的表示也非常重要。当我们写：<code>a ='ABC'</code>时，Python解释器干了两件事情：

1.  在内存中创建了一个<code>'ABC'</code>的字符串；
1.  在内存中创建了一个名为a的变量，并把它指向<code>'ABC'</code>。
```
最后，理解变量在计算机内存中的表示也非常重要。当我们写：<code>a ='ABC'</code>时，Python解释器干了两件事情：

1.  在内存中创建了一个<code>'ABC'</code>的字符串；
1.  在内存中创建了一个名为a的变量，并把它指向<code>'ABC'</code>。

PS:我尝试用其他在线Markdown编辑器进行编辑，结果解析正常，或许是因为Hexo的Markdown解析器自身的问题？
